### ISSUE TITLE
不带一些缓存之类的吗？

### ISSUE THREAD

**Issue by hongdong** [CoderJackyHuang/HYBNetworking#1]
不带一些缓存之类的吗？

**Comment by CoderJackyHuang** [comment]
若有此需要，我可以追加相关API操作。期待下一版本吧！


原始邮件
发件人:hongdongnotifications@github.com
收件人:CoderJackyHuang/HYBNetworkingHYBNetworking@noreply.github.com
发送时间:2016年1月13日(周三) 15:27
主题:[HYBNetworking] 不带一些缓存之类的吗？ (#1)


不带一些缓存之类的吗？

**Comment by hongdong** [comment]
赞、会持续关注
