### ISSUE TITLE
你好，使用你封装的这个库，调用新浪微博获取access token接口，400 bad request

### ISSUE THREAD

**Issue by maltsugar** [CoderJackyHuang/HYBNetworking#12]
换成AFHTTPSessionManager 就没问题

**Comment by CoderJackyHuang** [comment]
设置一下请求类型，默认为JSON的，如果不支持，修改成plaintext即可！

**Comment by maltsugar** [comment]
我试过了  接收类型加了 @"text/plain"， 不行的
而直接用afn ，不用加@"text/plain"是可以的
