### ISSUE TITLE
about steaming upload

### ISSUE THREAD

**Issue by lastObject** [CoderJackyHuang/HYBNetworking#13]
@CoderJackyHuang 
hi, i want ask some question about streaming upload, this is the problem for me.
the method you provide still need transfer image to nsdata, how about my file is big enough to make app crash.

our app is support iOS 7, and support video upload, when you file is big enough, the app will crash.

thanks.

**Comment by CoderJackyHuang** [comment]
I havn't supported stream upload, you should do it by yourself. NSURLSession provides stream delegate, you can just set the protocol, and you can get callback！
