### ISSUE TITLE
下载文件后，在文件夹中找不到！

### ISSUE THREAD

**Issue by TheCodeor** [CoderJackyHuang/HYBNetworking#14]
我用afnetwork里面的下载例子里面的获取路径的方法修改了一下，才可以看到下载完成后出现在document里面

![image](https://cloud.githubusercontent.com/assets/15356469/15466482/7afce68c-210c-11e6-8eb8-d8cf4e77957b.png)
 savePath只当成文件的名字

**Comment by CoderJackyHuang** [comment]
修改了一下，更新到3.2.2版本就好！当然不升级也可以，只是需要将file://传过去才能存储起来
