### ISSUE TITLE
参数传不过去

### ISSUE THREAD

**Issue by T1200** [CoderJackyHuang/HYBNetworking#17]
1.在进行Post或者Get请求时，在原有的+ (AFHTTPSessionManager *)manager进行创建时，参数传不到服务器，但是用原生的AFHTTPSessionManager创建就可以将参数传过去
2.难道大家在使用的时候都没有发现？感觉好郁闷啊...

**Comment by CoderJackyHuang** [comment]
配置请求参数类型为plainText


原始邮件
发件人:糖纸疯了notifications@github.com
收件人:CoderJackyHuang/HYBNetworkingHYBNetworking@noreply.github.com
发送时间:2016年6月20日(周一) 21:13
主题:[CoderJackyHuang/HYBNetworking] 参数传不过去 (#17)


1.在进行Post或者Get请求时，在原有的+ (AFHTTPSessionManager *)manager进行创建时，参数传不到服务器，但是用原生的AFHTTPSessionManager创建就可以将参数传过去
 2.难道大家在使用的时候都没有发现？感觉好郁闷啊...

**Comment by T1200** [comment]
[HYBNetworking-Question.zip](https://github.com/CoderJackyHuang/HYBNetworking/files/325259/HYBNetworking-Question.zip)
问题依然没有解决，写了一个小demo，你看一下，不能配置啊，配置后，直接请求错误，同样的方法，原声的AFNetWorking就可以请求，

**Comment by gdfyj90** [comment]
static HYBRequestType  sg_requestType  = kHYBRequestTypePlainText;
这样去改就可以了，我也是今天遇到了这个坑

**Comment by CoderJackyHuang** [comment]
鉴于大家经常遇到这样的问题，现在升级一个小版本，将请求头默认请求方式修改为text/plain形式了。相信大家就可以解决了！
