### ISSUE TITLE
我调用一个获取图片验证码的接口,返回 errorInfos:Request failed: unacceptable content-type: image/png

### ISSUE THREAD

**Issue by RabbitBell** [CoderJackyHuang/HYBNetworking#19]
获取图片验证码的接口,返回的是data.  调用这个库提示error,返回 errorInfos:Request failed: unacceptable content-type: image/png

**Comment by CoderJackyHuang** [comment]
没有指定image/png类型！


原始邮件
发件人:RabbitBellnotifications@github.com
收件人:CoderJackyHuang/HYBNetworkingHYBNetworking@noreply.github.com
发送时间:2016年7月5日(周二) 17:07
主题:[CoderJackyHuang/HYBNetworking] 我调用一个获取图片验证码的接口,返回 errorInfos:Request failed: unacceptable content-type: image/png (#19)


获取图片验证码的接口,返回的是data. 调用这个库提示error,返回 errorInfos:Request failed: unacceptable content-type: image/png

**Comment by RabbitBell** [comment]
怎么才能制定image/png类型? 在哪里?

**Comment by CoderJackyHuang** [comment]
内部写 image/*，应该是支持所有的图片类型了的！找到

```
      manager.responseSerializer.acceptableContentTypes = [NSSet setWithArray:@[@"application/json",
                                                                                @"text/html",
                                                                                @"text/json",
                                                                                @"text/plain",
                                                                                @"text/javascript",
                                                                                @"text/xml",
                                                                                @"image/*"]];
```

然后添加image/png试试！
