### ISSUE TITLE
updateBaseUrl判断

### ISSUE THREAD

**Issue by maotou** [CoderJackyHuang/HYBNetworking#21]
在+ (void)updateBaseUrl:(NSString *)baseUrl {
  if ([baseUrl isEqualToString:sg_privateNetworkBaseUrl] && baseUrl && baseUrl.length) {
    sg_isBaseURLChanged = YES;
  } else {
    sg_isBaseURLChanged = NO;
  }
  
  sg_privateNetworkBaseUrl = baseUrl;
}
这里第一个判断条件 [baseUrl isEqualToString:sg_privateNetworkBaseUrl] 是否应该添加非操作，只有新的baseURL与原来的baseURL不一样的时候，才可以证明baseURLchanged，请问是这样吗？

**Comment by spirit-jsb** [comment]
我也有这个疑惑！~

**Comment by maotou** [comment]
呼叫标哥~！

**Comment by CoderJackyHuang** [comment]
en


原始邮件
发件人:maotounotifications@github.com
收件人:CoderJackyHuang/HYBNetworkingHYBNetworking@noreply.github.com
发送时间:2016年7月21日(周四) 20:34
主题:Re: [CoderJackyHuang/HYBNetworking] updateBaseUrl判断 (#21)


呼叫标哥~！

**Comment by livv** [comment]
为啥这个问题还没有修复呢？

**Comment by CoderJackyHuang** [comment]
一直没更新，因为并不影响使用。已更新了！
