### ISSUE TITLE
如果需要传多张图片

### ISSUE THREAD

**Issue by gdfyj90** [CoderJackyHuang/HYBNetworking#3]
我发现你封装的api目前只有上传单张图片，如果传多张图是循环调用那个接口吗？还是传个数组然后循环调用appenddata方法就好？

**Comment by CoderJackyHuang** [comment]
那得看后台怎么接收了~一般不会多张同时上传，通常是一张一张地传。


原始邮件
发件人:gdfyj90notifications@github.com
收件人:CoderJackyHuang/HYBNetworkingHYBNetworking@noreply.github.com
发送时间:2016年2月27日(周六) 11:49
主题:[HYBNetworking] 如果需要传多张图片 (#3)


我发现你封装的api目前只有上传单张图片，如果传多张图是循环调用那个接口吗？还是传个数组然后循环调用appenddata方法就好？

**Comment by AgentEric** [comment]
我和上面的同学一个需求，如果作者能看到，看能不能写一个上传多张照片的API，这个需求还是蛮常见的，多谢了 。

**Comment by CoderJackyHuang** [comment]
你有上传多张图片的接口吗，不然我也没有办法测试！

**Comment by gdfyj90** [comment]
其实我的提问就是如果一张一张的传，是重复调用你提供的uploadWithImage接口。还是说改写uploadWithImage接口，把image参数变为一个包含image对象的数组。然后在constructingBodyWithBlock里面去循环上传？

**Comment by CoderJackyHuang** [comment]
递归上传。因为通常要求一张一张地成功上传，如果失败，不会因为失败而全部失败。


另外，要上传一个图片数组，那要求后台提供这样的接口，才能解析得了。


原始邮件
发件人:gdfyj90notifications@github.com
收件人:CoderJackyHuang/HYBNetworkingHYBNetworking@noreply.github.com
抄送:JackyHuang18675574495@163.com
发送时间:2016年3月1日(周二) 20:30
主题:Re: [HYBNetworking] 如果需要传多张图片 (#3)


其实我的提问就是如果一张一张的传，是重复调用你提供的uploadWithImage接口。还是说改写uploadWithImage接口，把image参数变为一个包含image对象的数组。然后在constructingBodyWithBlock里面去循环上传？
