### ISSUE TITLE
有一个API需要更新！谢谢

### ISSUE THREAD

**Issue by AgentEric** [CoderJackyHuang/HYBNetworking#5]
HYBNetworking.m line 500  （+ (NSString *)hyb_URLEncode:(NSString *)url ）

【CFStringRef CFURLCreateStringByAddingPercentEscapes(CFAllocatorRef allocator, CFStringRef originalString, CFStringRef charactersToLeaveUnescaped, CFStringRef legalURLCharactersToBeEscaped, CFStringEncoding encoding) CF_DEPRECATED(10_0, 10_11, 2_0, 9_0, "Use [NSString stringByAddingPercentEncodingWithAllowedCharacters:] instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent (since each URL component or subcomponent has different rules for what characters are valid).");】

**Comment by CoderJackyHuang** [comment]
这个是兼容性的API

**Comment by AgentEric** [comment]
什么意思？我不懂啊，请教一下，apple不是说它CF_DEPRECATED，使用[NSString stringByAddingPercentEncodingWithAllowedCharacters:] 代替吗？

**Comment by AgentEric** [comment]
是说不管什么编码规则他都可以吗？

**Comment by CoderJackyHuang** [comment]
这不影响使用，只是标识废弃了，但是一样可以使用


原始邮件
发件人:AgentEricnotifications@github.com
收件人:CoderJackyHuang/HYBNetworkingHYBNetworking@noreply.github.com
抄送:JackyHuang18675574495@163.com
发送时间:2016年3月1日(周二) 20:14
主题:Re: [HYBNetworking] 有一个API需要更新！谢谢 (#5)


是说不管什么编码规则他都可以吗？
