### ISSUE TITLE
未拼接BaseUrl和自己传入的url

### ISSUE THREAD

**Issue by 308823810** [CoderJackyHuang/HYBNetworking#8]

**Comment by CoderJackyHuang** [comment]
描述清楚一点！

**Comment by 308823810** [comment]
好的,if ([NSURL URLWithString:[NSString stringWithFormat:@"%@%@", [self baseUrl], url]] == nil) { 
只有拼接的判断,但是实际上并没有拼接在一起啊

**Comment by CoderJackyHuang** [comment]
这并不需要拼接啊。这只是为了判断是否是正确的URL。在必请求的地方，如果有BaseUrl，不需要拼接就可以请求了！

**Comment by 308823810** [comment]
为什么有的地方进行了拼接(例如上传文件),有的地方没有拼接(例如post),这样不会乱吗

**Comment by CoderJackyHuang** [comment]
不会啊~这两种不同嘛~
